# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 3
image:
  repository: abs-guide
  tag: 1
  pullSecret: regsecret
  pullPolicy: IfNotPresent
service:
  name: abs-guide-service
  type: NodePort
  externalPort: 80
  internalPort: 80
resources: {}